### ISSUE TITLE
Need minimum number of animation ACEs

### ISSUE THREAD

**Issue by MikalDev** [gritsenko/c3_spine_plugin#10]
Just the minimum to make complete enough to use in a game.
Conditions
- is playing
- -> on finished
- -> on any finished

**Comment by Bodhran** [comment]
Those would be awesome when added. Spine doesn't work on C2 since an update and would love to have spine working with Construct.

**Comment by gritsenko** [comment]
pushed those conditions

**Comment by MikalDev** [comment]
Thanks! Nice work.
