### ISSUE TITLE
Bug: After exporting lines appear on the sprites used on the spine animation.

### ISSUE THREAD

**Issue by Bodhran** [gritsenko/c3_spine_plugin#13]
After exporting the game the lines appear on the edges of sprites on the spine animation similar thing happens if the premutliply alpha is not checked in preview.

**Comment by MikalDev** [comment]
Do you have an example project you could share to help debug?

**Comment by Bodhran** [comment]
While making a test on my main computer it doesn't happen but with my other computer(really old) it does. It has something to do outside of Construct when building the game.

**Comment by MikalDev** [comment]
There may be a race condition with setting PMA, so it could have different behavior on different platforms. I have another update that may remove the race.

**Comment by MikalDev** [comment]
Added PR #15 for this.
