### ISSUE TITLE
Add animation mixes

### ISSUE THREAD

**Issue by gritsenko** [gritsenko/c3_spine_plugin#17]
We need to mix animations to make smooth transitions between them

**Comment by MikalDev** [comment]
How about at least adding ACEs to allow the setting of a default transition mix?

e.g.: 
stateData.setDefaultMix(x);

http://esotericsoftware.com/spine-applying-animations

**Comment by MikalDev** [comment]
Also requested by Artcadev: Mix feature from Spine, this is a really powerful feature that I often use on other runtimes from Spine2D, it basically allows you to blend between different animations, it is present both on editor as well in other runtimes such as Unity,  Unreal and GMS2 I believe.
http://esotericsoftware.com/spine-applying-animations#Mix-times

**Comment by MikalDev** [comment]
From spine-ts example transitions demo:

`	function createState (mix) {
		var stateData = new spine.AnimationStateData(skeleton.data);
		stateData.defaultMix = mix;
		var state = new spine.AnimationState(stateData);
		return state;
	}`

**Comment by MikalDev** [comment]
Added property for default mix in release 1.5.0. Open new issue if other mix features are required.
