### ISSUE TITLE
Problem starting animation queue

### ISSUE THREAD

**Issue by starkiJi** [gritsenko/c3_spine_plugin#19]
The game skips all "On animation finished" animations and launches the latest animation, immediately after the end of the animation - Intro

**Link image** - https://ibb.co/DDYq2K0

**Game .c3p file** - https://cloud.mail.ru/public/3Ra9/4nSp6MVve

**Comment by MikalDev** [comment]
Thanks for the report and the clear example, I'll take a look at this.

**Comment by MikalDev** [comment]
I did a fix for this (1.4.6), @starkiJi please try it and close the issue if it works for you.

Latest version is avaiable at:
https://gritsenko.github.io/c3_spine_plugin/

**Comment by starkiJi** [comment]
Thank you! 1.4.6 Works

**Comment by MikalDev** [comment]
Great! Closing issue.
