### ISSUE TITLE
Questions on 'Keep Aspect Ratio' property

### ISSUE THREAD

**Issue by MikalDev** [gritsenko/c3_spine_plugin#26]
@gritsenko, great to see more contributions to the addon!

Can you provide more details on the Keep Aspect Ratio property?

When I apply this to the sample project with a scale of 1.0, the Spine object renders so that only part of the character is visible. Are there other settings / sizes for the object / project to use to make it work as expected? I tried resizing the C3 Spine object size, but couldn't quite find something that worked.

**Comment by gritsenko** [comment]
You can use Scale property to control size of character and resize object itself to ajust bounds of viewport.

**Comment by gritsenko** [comment]
but yeah... we probably need more smart way to control size of character

**Comment by MikalDev** [comment]
Ok, got it. The way I have been using recently is in Spine project, placing an invisible image sized to how to how big a bounding box I want for all the character and all the animations (eg including lunges, falling dead, etc.) I can then use a scale of ‘1’. To set the proper aspect ratio of the C3 spine object, I can use a common ratio to scale the C3 object using the new texture expressions width/height. So far it’s working out pretty well, but does require events to to do the scaling.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
