### ISSUE TITLE
Collisions?

### ISSUE THREAD

**Issue by Visual917** [gritsenko/c3_spine_plugin#36]
This loads the animations as a single PNG. How are we supposed to work with collisions? :P ...or are we, at all?

**Comment by MikalDev** [comment]
I usually pin/place an invisible collision box Sprite to the Spine instance, then if needed use additional offset collision boxes for longer range melee weapon strikes and use Spine ‘events’ to trigger attack collision/overlap checks. eg add an OnDamage event at the moment when a sword strike should do damage.

**Comment by MikalDev** [comment]
That being said, I am also experimenting with adding at least an expression to get a Spine bounding box attachment center which is updated with the animation.  They could be used as reference for C3 collision sprites (e.g. body center, sword tip as it swings, etc.)

**Comment by Visual917** [comment]
Awesome. Spriter (and its plugin) is so problematic so I was thinking of switching to Spine. We'll see.

**Comment by MikalDev** [comment]
Added bounding ACEs to plugin in release 1.18.0

https://github.com/gritsenko/c3_spine_plugin/commit/c86c5e2866beb0730bc546ff9f04564f03aceb87
