### ISSUE TITLE
Request: Set animation mix duration via events

### ISSUE THREAD

**Issue by birbdoy** [gritsenko/c3_spine_plugin#37]
An action to dynamically set animation mix duration would be fantastic. 
A simple example where this would be beneficial: you could use a long mix duration when your character goes from running to idle while decelerating but a very short mix duration when switching to an attack animation so the input feels snappy and direct.

**Comment by MikalDev** [comment]
So this will probably be set for all instances of an object, see:
http://en.esotericsoftware.com/spine-applying-animations#Mix-times.

My thought is to make a new ACE: Set animation mix from {0} to {1} of {2}, {0} is animation from, {1} is animation to, {2} is mix duration in seconds.

**Comment by MikalDev** [comment]
It looks like we are create animation stateDate per instance, so it may actually only effect the picked instances. I would recommend setting it before mixing animations, I am not sure what would happen if the value was changed mid mix.

**Comment by MikalDev** [comment]
Please try version 1.19.0

1.19.0 Add Set animation mix {fromName} to {toName} with duration {seconds}. I did some light testing with a single instance. Please report back on how it works for you.

**Comment by birbdoy** [comment]
Works great so far! I'll let you know if I stumble upon anything weird.
