### ISSUE TITLE
How to correctly to handle character translation or bounds change?

### ISSUE THREAD

**Issue by MikalDev** [gritsenko/c3_spine_plugin#5]
Using the Spineboy character, when the character 'jumps' it goes outside the resolution of the texture being rendered to, so it clips, how to handle this case? Is it a translation issue (e.g. need to anchor animation to a certain point, or do we need to adjust the texture size? Hacking a change to increase the texture size, but not the viewport worked for Spineboy rendering, but is not the correct solution. When using a character as a sprite, it seems like animations should not 'translate' instead the Sprite will translate (e.g. the sprite itself will jump.)

**Comment by gritsenko** [comment]
Just added Scale property to spine object. Not the best option. but at least we have workaround.

**Comment by MikalDev** [comment]
Recommendation added to readme file: don't do large translates in spine project or add bounding box image to Spine project, so render is scaled.
