### ISSUE TITLE
spine-runtimes 4.0

### ISSUE THREAD

**Issue by avatar45D** [gritsenko/c3_spine_plugin#56]
Please add support runtime 4 spine-webgl.js
Simply replacing the spine-webgl.js 3.8> 4.0 script in the plugin doesn't help

**Comment by MikalDev** [comment]
This will require changes and updates due to the changed API for  assets / shared assets. My estimate, if I do the change, is that I will likely have some time to do the change in 1-2 months.

**Comment by MikalDev** [comment]
Initial beta release now available (version 2.0.0)
