### ISSUE TITLE
The game freezes while reading the save

### ISSUE THREAD

**Issue by reimuxx** [gritsenko/c3_spine_plugin#81]
Hi, I am using the translation software, so I have some problems in the expression of words. I will try my best to express this problem concisely.

1. Save in a scene of newly generated bones
2. Switch to another scenario
3. Read the archive and crash
[bug.zip](https://github.com/gritsenko/c3_spine_plugin/files/8229047/bug.zip)

**Comment by odiusfly** [comment]
I have the same issue with save/load. Any help? Thanks!

**Comment by MikalDev** [comment]
I don't yet have a fix for the plug-in for this.

I suggest a workaround:
- Associate Spine objects with sprites, used as control objects (like a sprite controller object for the player, including position, direction, spine animation).
- Apply the 'No Save' behavior to the Spine object(s).
- When loading a game, add a Spine Destroy ACE before calling load.
- On Game Load complete loop through the Spine controller sprites and create a Spine object based on the Sprite controller (position, direction, animation state, etc.)

**Comment by MikalDev** [comment]
Example workaround:
[bug-workaround.c3p.zip](https://github.com/gritsenko/c3_spine_plugin/files/8759461/bug-workaround.c3p.zip)

**Comment by odiusfly** [comment]
@MikalDev  Thanks for the tip! My project it's a bit different but i will try this way - maybe will work too.
I hope to find a fix solution for the addon soon. All the best!
