### ISSUE TITLE
Set animation & mix issues

### ISSUE THREAD

**Issue by alinj-13** [gritsenko/c3_spine_plugin#87]
Assume that my default mix is 0.2 and animation A is playing, 
Sometimes, when I press a key to run anim B, it doesn't work well (kinda shows some frames of anim B then quickly goes to anim A)
and sometimes it works. 

EDIT: the issue happens when I added this part:
On animation B finished  > wait 0 seconds , start anim A

Thanks for the awesome work. hope to see a quick fix!

**Comment by MikalDev** [comment]
Can you please provide an example project showing this issue, much easier for me to debug. Thanks!

**Comment by alinj-13** [comment]
[link here](https://drive.google.com/file/d/1pCaVHlDyAPXqVMu6lHJwgafrkOTSyDxg/view?usp=sharing)
please hit Number 2 on keyboard to show "start" animation. try on different timelines to see the bug.
thanks!

**Comment by MikalDev** [comment]
Thanks for the example, I don't think I see the issue yet. I modified the example to not use waits, because I find that they can cause behavior that might be different than I expect.

https://sendgb.com/Au3g5ZnqbIX

If you still see the issue with my changes, can you give me more details on how to cause the issue and a video showing the issue?

**Comment by arcadesindo** [comment]
[skate game _ anim (1).zip](https://github.com/gritsenko/c3_spine_plugin/files/10866894/skate.game._.anim.1.zip)
oopsie sorry, I think I've destruct the link, here mikal's file

**Comment by alinj-13** [comment]
Hi. I checked the source you sent. got an error: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."
However, I recorded my screen for both modes (with or without waits). please check:
[Link](https://drive.google.com/file/d/1wjbFRWGcUdi0dHzQOitYn6zSeHho5fWm/view?usp=sharing)

**Comment by arcadesindo** [comment]
[New folder.zip](https://github.com/gritsenko/c3_spine_plugin/files/10868310/New.folder.zip)
hmm try this

**Comment by MikalDev** [comment]
The project I sent is saved using the latest beta, please open it the latest beta:

https://editor.construct.net/r332/

**Comment by alinj-13** [comment]
I definitely used the last version:  https://editor.construct.net/r332/
still got error: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

**Comment by MikalDev** [comment]
I think the other person who downloaded it and then uploaded it again might have corrupted the file, please try again here's another link: https://sendgb.com/X0ys8e17zch

For your recording, are the events automated (e.g. the issue is happening without user input), if so, can you also send me that project, hopefully I can replicate it on my side, so I can debug.

**Comment by alinj-13** [comment]
I don't know what's the problem but again, got this error: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

as I explained and showed in the videos, the issue is happening by hitting key 2 on keyboard. but it's not the input issue. it's related to the mix value. I'm sure about this because when I set mix to 0, then everything is fine. but I need to use mix for my game. the source file I showed in the videos is exactly the same that I sent to you. I just added a log text at top. 

Hope to see you guys fix the issue because the team is waiting for the project asap. I don't know how much the work cost, but I'm pretty sure that we'll donate some money for the job. thanks again!

**Comment by alinj-13** [comment]
@JeFawk I tried as you said. not working. 
@MikalDev I think that is not related to the Construct file because I did everything as the plugin doc and also used/ not used waits in the projects. 
I think it's related to the plugin. it must consider the last played animation as the main animation and run it well. Please let me know that you agree or not.
I really appreciate if you(/dev team) review the plugin to see if there's a way to fix the issue. thanks!

**Comment by MikalDev** [comment]
I am looking at it, trying to automate a way to make it fail, so I can instrument it (and it is just me supporting now, I am not connected with esoteric sw, this is all done on a voluntary basis.) I should have more time to look at it early next week.

**Comment by alinj-13** [comment]
@MikalDev That's great news! Looking forward to hearing from you!

**Comment by alinj-13** [comment]
Hello @MikalDev and team!
Any news?
