### ISSUE TITLE
Settings of json export for use in construct 3

### ISSUE THREAD

**Issue by rafieimohammad82** [gritsenko/c3_spine_plugin#91]
Hi guys;
I want to get json export for my project and use it in construct3, but it doesn't work in construct3 (bones doesn't move in software) . I think this problem happens because of output settings. Please, give me a picture of output settings for use in the construct 3. 
Thanks

**Comment by MikalDev** [comment]
What version of spine are you using? Can you share your c3 project?

**Comment by rafieimohammad82** [comment]
> What version of spine are you using? Can you share your c3 project?

Thank you for your answer. my spine version is 3.8.75 professional and this is my project:
https://www.dropbox.com/s/s3h6u8zappq14l6/Spine_test.zip?dl=0

**Comment by rafieimohammad82** [comment]
The character's hands must move, but character only blink.

**Comment by rafieimohammad82** [comment]
> Ah! You need to use Spine 4.1 and export with it to be compatible with the current addon.

Ok, thanks. I will test it.
