### ISSUE TITLE
3DCamera is not supported

### ISSUE THREAD

**Issue by ooonush** [gritsenko/c3_spine_plugin#92]
If you use a 3D layer and a 3D camera that tracks the character, the animation does not work correctly (does not bounce). This happens because the 2D camera stands still and looks at the top left of the layout (Viewport). Since the 3D camera follows the character, the 2D camera stays in place. And when the character leaves the viewport area, the animations start to work incorrectly (this is probably due to optimization).

**Comment by MikalDev** [comment]
Thanks for reporting, will check this out. Meanwhile, if you a a simple example test project that shows this issue, it will definitely help with debug. I use sendgb.com to share files or you can attach here too.

**Comment by tatosgames** [comment]
it happens to me with some cases but with a basic 3d shape on it it doesn't happens
![image](https://github.com/gritsenko/c3_spine_plugin/assets/3294453/30ecbeea-2968-4568-b013-a0c0115dafb9)
![image](https://github.com/gritsenko/c3_spine_plugin/assets/3294453/9f0548c3-d09b-4001-b83f-642555ce0d9c)
Maybe something with blending alpha?

**Comment by MikalDev** [comment]
If you can provide an example with the issue and some quick instructions how to show the issue, it will enable me to debug.

**Comment by MikalDev** [comment]
No sample provided, so closing. Please feel free to repopen if an example is available.
