### ISSUE TITLE
Transparency Issue in Spline When Using Mixed Effects for Slots

### ISSUE THREAD

**Issue by TamaniDamani** [gritsenko/c3_spine_plugin#95]
![image](https://github.com/gritsenko/c3_spine_plugin/assets/76815897/fecb3400-ab8a-46c0-88ae-d5360bcbf2f6)
In Spline, using mixed effects for a slot can result in the slot becoming semi-transparent and showing the background.

**Comment by MikalDev** [comment]
Can you share an example project and point out the specific issues in the above image?

**Comment by MikalDev** [comment]
Closing until reply on this request.
