### ISSUE TITLE
Webgpu support

### ISSUE THREAD

**Issue by elfwy-uwu** [gritsenko/c3_spine_plugin#96]
It seems that c3 spine currently doesn't support webgpu renderer as using examples from github page and setting renderer to webgpu doesn't work. I saw [this thread](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/webgpu-renderer-allow-webgpu-164365) on construct forum and it looks like you were interested in implementing the feature, tho it was 2 years ago and webgpu wasn't a thing. And now when webgpu released and became more stable in construct, are there any plans on supporting it and if yes, are there possible performance benefits?

**Comment by MikalDev** [comment]
No plans at the moment and the webgpu may not perform as well, because it will need to use the higher level C3 SDK, which does not support two color tinting well (requires breaking of batch) and may not be as efficient as the Spine direct webgl implementation.

**Comment by MikalDev** [comment]
Closing for now, I did request that esoteric s/w create an official C3 addon, which would support webgpu.
