### ISSUE TITLE
Need help adding new functionality 4.2 - Physics

### ISSUE THREAD

**Issue by avatar45D** [gritsenko/c3_spine_plugin#97]
As a wish, it would be nice to add support for the new powerful functionality of version 4.2 Physics to webgl
PhysicsConstraint
PhysicsConstraintData
Currently the plugin uses spine-runtimes-4.1
New functionality has been added to spine-runtimes-4.2
Best wishes and thank you!

**Comment by MikalDev** [comment]
Please review: https://github.com/gritsenko/c3_spine_plugin/releases/tag/2.9.0

Thanks to the donation, I sped up work on this.

Please test, I have not done much with physics myself, so I don't what additional ACEs (if any) are needed.

I did add the ACE Set physics mode w/ the default being 'update'

If you have a physics project to share, post a link here or send me a DM on Construct Community Discord server, so I can help further test.

**Comment by MikalDev** [comment]
One item we saw in our testing going from 4.1 -> 4.2, we had to add the following settings:
<img width="474" alt="Screenshot 2024-05-14 at 5 08 58 PM" src="https://github.com/gritsenko/c3_spine_plugin/assets/33675273/be54716f-da4a-4669-81c8-f6bf5642c302">

**Comment by avatar45D** [comment]
[physics test.zip](https://github.com/gritsenko/c3_spine_plugin/files/15370491/physics.test.zip)
Everything is fine and thank you, but the physics animation is not played as it should in constructor 3 (Spine model in attachment) The name of the animation being tested is "swing"

**Comment by MikalDev** [comment]
Is this correct? I changed the project to use webGL2 (instead of Auto, which picks webGPU on my setup). This addon only supports webGL2, webGPU is nit supported. There may be an official esoteric SW addon coming, which uses the C3 SDK directly and would with webGPU and webGL2. However that depends on when SDK V2 will be finished and if it supports more than the basic features.

![swing](https://github.com/gritsenko/c3_spine_plugin/assets/33675273/6699365b-7345-4708-b2f0-c964af0c59af)

**Comment by avatar45D** [comment]
Yes, I know that webGPU is not supported, this is not webgl. The animation should be smoother
![celestial-circus-pro-wind-idle](https://github.com/gritsenko/c3_spine_plugin/assets/57419236/2641abe9-072d-4e4c-8e16-ffd82931f696)

**Comment by MikalDev** [comment]
I see, thanks for the visual, I will explore more.

**Comment by MikalDev** [comment]
Got a fix, will test a bit more and release tomorrow. The visual was a big help with debug, thanks for that.

**Comment by avatar45D** [comment]
> Got a fix, will test a bit more and release tomorrow. The visual was a big help with debug, thanks for that.

Thank you for doing this!

**Comment by MikalDev** [comment]
Updated see release:

https://github.com/gritsenko/c3_spine_plugin/releases/tag/2.9.1
